version: '3'
services:

  vncmux:
    restart: unless-stopped
    build: ./vncmux
    command: "sh -c 'sleep 2 && /vncmux -l 5900 -w ${pixelflut_canvas_width} -h ${pixelflut_canvas_height} ${pixelflut_host} ${pixelflut_port_vnc}'"
    network_mode: "host"

  statistics_crawler:
    restart: unless-stopped
    build: ./statistics_crawler
    command: "python3 crawl.py ${pixelflut_host} ${pixelflut_port_statistics} /tmp/pixelflut_statistics.txt"
    volumes:
      - "./pixelflut_statistics.txt:/tmp/pixelflut_statistics.txt"

  node_exporter:
    restart: unless-stopped
    image: "prom/node-exporter:v1.3.1"
    command: "--collector.textfile.directory /var/lib/node_exporter/textfile_collector"
    volumes:
      - "./pixelflut_statistics.txt:/var/lib/node_exporter/textfile_collector/pixelflut_statistics.prom"

  prometheus:
    restart: unless-stopped
    image: "prom/prometheus:v2.32.1"
    volumes:
      - "./prometheus/pixelflut.yml:/etc/prometheus/prometheus.yml"
      - 'prometheus-data:/prometheus'
    links:
      - node_exporter

  grafana:
    restart: unless-stopped
    image: grafana/grafana:8.3.3
    ports:
      - 80:3000
    links:
      - prometheus
    volumes:
      - './grafana/provisioning:/etc/grafana/provisioning/'
      - 'grafana-data:/var/lib/grafana'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "${grafana_admin_password}"
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_USERS_AUTO_ASSIGN_ORG: 'true'
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: 'Admin'

volumes:
  grafana-data:
  prometheus-data:
