version: '3'
services:

  # shoreline:
  #   restart: unless-stopped
  #   image: ghcr.io/poeschl/shoreline
  #   entrypoint: ["shoreline", "-b", "0.0.0.0", "-p", "1234", "-f", "vnc,port=5901", "-f", "statistics,port=1235", "-t", "arial.ttf"]
  #   command: -w ${pixelflut_canvas_width} -h ${pixelflut_canvas_height} -d "${pixelflut_description}"
  #   network_mode: "host"

  #breakwater:
  #  restart: unless-stopped
  #  image: sbernauer/breakwater:0.0.9
  #  entrypoint: ["breakwater", "-l", "[::]:1234", "--vnc-port", "5901"]
  #  command: -w ${pixelflut_canvas_width} -h ${pixelflut_canvas_height} -t "${pixelflut_description}"
  #  network_mode: "host"

  glances:
    image: nicolargo/glances:3.2.5-full
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      GLANCES_OPT: "--quiet --export prometheus"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances/pixelflut-config.conf:/glances/conf/glances.conf
