version: '3'
services:

  breakwater:
    restart: unless-stopped
    image: sbernauer/breakwater:0.12.0
    entrypoint: ["breakwater", "-l", "[::]:1234", "--vnc-port", "5901"]
    command: --width ${pixelflut_canvas_width} --height ${pixelflut_canvas_height} --text "${pixelflut_description}"
    network_mode: "host"

  glances:
    image: nicolargo/glances:3.4.0.3-full
    restart: unless-stopped
    network_mode: host
    pid: host
    environment:
      GLANCES_OPT: "--quiet --export prometheus"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances/pixelflut-config.conf:/glances/conf/glances.conf
