global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'system_glances'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'host.docker.internal:9091'
        - 'host.pixelflut:9091'

  - job_name: 'pixelflut_statistics'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'shoreline_exporter:7979'

  - job_name: 'breakwater_statistics'
    static_configs:
      - targets:
        - 'host.pixelflut:9100'
