{
 "title": "Pixelflut overview",
 "tags": [
  "pixelflut",
  "breakwater"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Connected IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "breakwater_ips" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(breakwater_connections) or vector(0)"
    }
   ]
  },
  {
   "title": "FPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "breakwater_fps" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(breakwater_bytes[1m])) * 8  or vector(0)"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(breakwater_bytes) or vector(0)"
    }
   ]
  },
  {
   "title": "Pixels / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(breakwater_pixels[1m])) * 8  or vector(0)"
    }
   ]
  },
  {
   "title": "Total Pixels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(breakwater_pixels) or vector(0)"
    }
   ]
  },
  {
   "title": "Connected IPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "breakwater_ips", "legendFormat": "All" },
    { "expr": "breakwater_legacy_ips", "legendFormat": "IPv4" }
   ]
  },
  {
   "title": "Traffic / IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(breakwater_bytes[$__interval]) * 8",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Connections / IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "breakwater_connections", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Pixels / s / IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(breakwater_pixels[$__interval]) * 8",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "FPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "targets": [
    { "expr": "breakwater_fps{}", "legendFormat": "Measured" },
    { "expr": "30", "legendFormat": "30 FPS" }
   ]
  }
 ]
}