{
 "title": "Monitoring Host",
 "tags": [ "system" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Core",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "glances_cpu_cpucore{type=\"monitoring\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "glances_cpu_cpucore{type=\"monitoring\"}*2",
     "legendFormat": "Good"
    },
    {
     "alias": "5mins",
     "column": "min5",
     "expr": "glances_load_min1{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "1min",
     "select": [
      [
       { "params": [ "min5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    },
    {
     "alias": "15mins",
     "column": "min15",
     "expr": "glances_load_min5{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "5min",
     "select": [
      [
       { "params": [ "min15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    },
    {
     "alias": "15mins",
     "column": "min15",
     "expr": "glances_load_min15{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "15min",
     "select": [
      [
       { "params": [ "min15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "load"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "column": "total",
     "expr": "glances_processcount_total{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "series": "processcount"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "glances_cpu_total{type=\"monitoring\"}",
     "legendFormat": "total"
    },
    {
     "alias": "User",
     "column": "user",
     "expr": "glances_cpu_user{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "user",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "System",
     "column": "system",
     "expr": "glances_cpu_system{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "system",
     "select": [
      [
       { "params": [ "system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    },
    {
     "alias": "IoWait",
     "column": "iowait",
     "expr": "glances_cpu_iowait{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "iowait",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "cpu"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "expr": "glances_mem_used{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Used",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem"
    },
    {
     "alias": "Max",
     "column": "total",
     "expr": "glances_mem_total{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Max",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "mem"
    }
   ]
  },
  {
   "title": "Network interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "alias": "In",
     "column": "enp0s25.rx",
     "expr": "glances_network_ens192_rx{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "In",
     "select": [
      [
       { "params": [ "eth0.rx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    },
    {
     "alias": "Out",
     "column": "eth0.tx*-1",
     "expr": "glances_network_ens192_tx{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Out",
     "select": [
      [
       { "params": [ "eth0.tx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "network"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used",
     "column": "used",
     "expr": "glances_memswap_used{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Used",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap"
    },
    {
     "alias": "Max",
     "column": "total",
     "expr": "glances_memswap_total{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "legendFormat": "Max",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "memswap"
    }
   ]
  },
  {
   "title": "disk IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Read",
     "column": "sda2.read_bytes",
     "expr": "glances_diskio_sda_read_bytes{type=\"monitoring\"} / glances_diskio_sda_time_since_update{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Read",
     "select": [
      [
       { "params": [ "sda2.read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    },
    {
     "alias": "Write",
     "column": "sda2.write_bytes",
     "expr": "glances_diskio_sda_write_bytes{type=\"monitoring\"} / glances_diskio_sda_time_since_update{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Write",
     "select": [
      [
       { "params": [ "sda2.write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "diskio"
    }
   ]
  },
  {
   "title": "/ Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Max",
     "column": "\"/.size\"",
     "expr": "glances_fs__etc_hostname_used{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Used",
     "select": [
      [
       { "params": [ "/.size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    },
    {
     "alias": "Used",
     "column": "\"/.used\"",
     "expr": "glances_fs__etc_hostname_size{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Max",
     "select": [
      [
       { "params": [ "/.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  {
   "title": "/ used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "column": "\"/.percent\"",
     "expr": "glances_fs__etc_hostname_percent{type=\"monitoring\"}",
     "function": "mean",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "/.percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "series": "fs"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Container CPU consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "label_replace({__name__=~\"glances_docker_.*_cpu_percent\", __name__!~\".*_runner_.*\", type=\"monitoring\"}, \"container\", \"$1\", \"__name__\", \"glances_docker_(.*)_cpu_percent\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{container}}",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "label_replace({__name__=~\"glances_docker_.*_memory_usage\", __name__!~\".*_runner_.*\", type=\"monitoring\"}, \"container\", \"$1\", \"__name__\", \"glances_docker_(.*)_memory_usage\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{container}}",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Net In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "label_replace({__name__=~\"glances_docker_.*_network_rx\", __name__!~\".*_runner_.*\", type=\"monitoring\"}, \"container\", \"$1\", \"__name__\", \"glances_docker_(.*)_network_rx\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{container}}",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Net Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "label_replace({__name__=~\"glances_docker_.*_network_tx\", __name__!~\".*_runner_.*\", type=\"monitoring\"}, \"container\", \"$1\", \"__name__\", \"glances_docker_(.*)_network_tx\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{container}}",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "label_replace({__name__=~\"glances_docker_.*_io_r\", __name__!~\".*_runner_.*\", type=\"monitoring\"}, \"container\", \"$1\", \"__name__\", \"glances_docker_(.*)_io_r\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{container}}",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "CPU%",
     "expr": "label_replace({__name__=~\"glances_docker_.*_io_w\", __name__!~\".*_runner_.*\", type=\"monitoring\"}, \"container\", \"$1\", \"__name__\", \"glances_docker_(.*)_io_w\")",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "{{container}}",
     "select": [
      [
       { "params": [ "grafana.cpu_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}