{
 "title": "Pixelflut statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pixel / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(pixelflut_pixels[1m])" }
   ]
  },
  {
   "title": "Pixels",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pixelflut_pixels" }
   ]
  },
  {
   "title": "Bit / s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "rate(pixelflut_bytes[1m])*8" }
   ]
  },
  {
   "title": "Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "pixelflut_bytes" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pixelflut_connections" }
   ]
  },
  {
   "title": "FPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    { "expr": "pixelflut_fps" }
   ]
  }
 ]
}