{
 "title": "Pixelflut statistics",
 "tags": [
  "pixelflut",
  "shoreline"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pixel / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Px/s" } },
   "targets": [
    {
     "expr": "shoreline_statistics_throughput_pixels"
    }
   ]
  },
  {
   "title": "Pixels",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "shoreline_statistics_traefik_pixel"
    }
   ]
  },
  {
   "title": "Bytes / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "shoreline_statistics_throughput_bytes"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "shoreline_statistics_traefik_bytes"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "shoreline_statistics_connections"
    }
   ]
  },
  {
   "title": "FPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    { "expr": "shoreline_statistics_fps" },
    { "expr": "60", "legendFormat": "60 Hz" }
   ]
  }
 ]
}