---
- name: Setup Pixelflut host
  hosts: all
  vars:
    apt_upgrade: true
    install_docker: true
    working_dir: ~/pixelflut-infrastructure

  tasks:

    - import_tasks: tasks/apt-upgrade.yaml
    - import_tasks: tasks/install-docker.yaml
    - import_tasks: tasks/workspace.yaml

    - name: Copy assets
      loop:
        - wiper
        - glances
        - .env
        - docker-compose.pixelflut-host.yml
      copy:
        src: "../{{ item }}"
        dest: "{{ working_dir}}"

    - name: Start Pixelflut docker container
      community.docker.docker_compose:
        project_src: "{{ working_dir }}"
        files:
          - docker-compose.pixelflut-host.yml

    - name: Install iptables
      become: true
      apt:
        pkg:
          - iptables
        update_cache: yes

    - name: Set up iptables rules
      become: true
      template:
        src: iptable-rules
        dest: /etc/network/if-pre-up.d/pixelflut-rules
        mode: 'a+x'

    - name: Execute iptables rules
      become: true
      shell:
        cmd: /etc/network/if-pre-up.d/pixelflut-rules
